ALTER TABLE ticket ADD COLUMN IF NOT EXISTS tipo_moneda VARCHAR(3);
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS monto_pagado REAL;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS cambio_entregado REAL;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS devolucion BOOLEAN NOT NULL DEFAULT FALSE;